name: geosib
description: "GeoSib - Геоматериалы, на которых стоит Сибирь"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0   # ← только одна строка!

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo.png      # ← положи сюда свой PNG логотип